<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="/struts-tags" prefix="s" %>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!-- Generated by F12 developer tools. This might not be an accurate representation of the original source file -->
<HTML>
<HEAD>
<TITLE>登录LoginUI</TITLE>
<SCRIPT type="text/javascript">
	if (document.layers) {
		document.write("<style>td{padding:0px;}<\/style>")
	}
</SCRIPT>
<META content="text/html; charset=utf-8" http-equiv=Content-type>
<META http-equiv="Window-target" content="_top">
<META content=no-cache http-equiv=Pragma>
<META content=no-cache http-equiv=Cache-Control>
<META content=no-cache http-equiv=Pragma-directive>
<META content=no-cache http-equiv=Cache-Directive>
<META content="Thu, 31 Dec 2015 08:51:45 GMT" http-equiv=Expires>
<META name=robots content=noindex,follow>
<!-- ${pageContext.request.contextPath }/style/ -->
<LINK rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/style/css/default.css">
<SCRIPT type=text/javascript>
	var loading_lang = "正在载入...";
</SCRIPT>

</HEAD>
<BODY windowc_onresizez="true">
	<DIV align=center>
		<A href="#"><IMG border=0 alt=loginUI
			src="images/login_logo.png"></A>
	</DIV>
	<BR>
	<DIV align=center></DIV>
	<!-- Login Form BEGIN -->
	<BR>
	<DIV align=center>
		<!-- <FORM method=post name=login_form action=login.php
			360chrome_form_autofill="2"> -->
		<s:form action="user_login">
			<TABLE class=width50 cellSpacing=1>
				<TBODY>
					<TR>
						<TD class=form-title><INPUT name=return value=index.php
							type=hidden> 登录</TD>
						<TD class=right></TD>
					</TR>
					<TR class=row-1>
						<TD class=category>帐号</TD>
						<TD><INPUT name=username maxLength=32 size=32></TD>
					</TR>
					<TR class=row-2>
						<TD class=category>密码</TD>
						<TD><INPUT name=password maxLength=1024 value="" size=32
							type=password></TD>
					</TR>
					<TR class=row-1>
						<TD class=category>在此浏览器上保留我的登录信息</TD>
						<TD><INPUT name=perm_login value="" type=checkbox></TD>
					</TR>
					<!-- <TR class=row-2>
						<TD class=category>安全会话</TD>
						<TD><INPUT name=secure_session value="" CHECKED type=checkbox>
							<SPAN class=small>仅允许通过本IP使用你的会话。</SPAN></TD>
					</TR> -->
					<TR>
						<TD class=center colSpan=2><INPUT class=button value=登录
							type=submit></TD>
					</TR>
				</TBODY>
			</TABLE>
		</s:form>
		<!-- </FORM> -->
		
	</DIV>
	<BR>
	<DIV align=center>
		<!-- <SPAN class=bracket-link>[&nbsp;<A href="signup_page.php">注册一个新帐号</A>&nbsp;]
		</SPAN>  -->&nbsp;<SPAN class=bracket-link>[&nbsp;<A
			href="lost_pwd_page.php">忘记密码？</A>&nbsp;]
		</SPAN>
	</DIV>
	<!-- Autofocus JS -->
	<SCRIPT language=JavaScript type=text/javascript>
	<!--
		window.document.login_form.username.focus();
	// -->
	</SCRIPT>
	<BR>
	<HR SIZE=1>

	<TABLE border=0 cellSpacing=0 cellPadding=0 width="100%">
		<TBODY>
			<TR vAlign=top>
				<TD>
					<ADDRESS>Copyright © 2016 csii_mas</ADDRESS>
				</TD>
				<TD></TD>
			</TR>
		</TBODY>
	</TABLE>
</BODY>
</HTML>
<%-- <html>
  <head>
    <base href="<%=basePath%>">
    
    <title>My JSP 'login.jsp' starting page</title>
    
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
	<meta http-equiv="description" content="This is my page">
	<!--
	<link rel="stylesheet" type="text/css" href="styles.css">
	-->

  </head>
  
  <body>
	<s:form action="user_login">
		<s:fielderror/>
		姓名：<s:textfield name="username"/><br/>
		密码：<s:password name="password"/>
		<s:submit value="提交"/>
	</s:form>
  </body>
</html> --%>
